name: zava_mcp_server

# Note: PostgreSQL is now deployed to Azure
# Local PostgreSQL container has been removed since we use Azure Database for PostgreSQL

services:
  # Placeholder service to maintain valid Docker Compose structure
  placeholder:
    image: alpine:latest
    command: echo "Using Azure PostgreSQL - no local services needed"
