[project]
name = "github-shop-agents"
version = "0.1.0"
description = "Agent implementations for the shop application"
requires-python = ">=3.12"
dependencies = [
    "agent-framework-core>=1.0.0b251016",
    "azure-identity>=1.23.0,<2.0.0",
]


[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"
