services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    environment:
      # Azure PostgreSQL configuration will be loaded from .env file
      - AZURE_EXTENSION_USE_DYNAMIC_INSTALL=yes_without_prompt
